#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication explicitLaplacianFoam

if false 
then
    runApplication foamToVTK
fi

#------------------------------------------------------------------------------
